### ISSUE TITLE
How about BiocExplorer instead of BioCExplorer?

### ISSUE THREAD

**Issue by hpages** [Shians/BiocExplorer#14]
Hi, I was wondering if you would consider renaming the package Bio**c**Explorer (instead Bio**C**Explorer) to be consistent with all the other existing Bioconductor packages that start with "Bioc": BiocInstaller, BiocCheck, BiocGenerics, BiocParallel, BiocFileCache, etc... Thanks!  H.

**Comment by Shians** [comment]
[Done](https://github.com/Shians/BioCExplorer/commit/d5fb64e10055304354a54c5851e380eb4529f3b9)! I guess my preference to read it as bio-see rather than bi-ock influenced my casing. Though I do wonder if I should deliberately have it look off-brand to distinguish it from well maintained and actually useful Bioc projects.

**Comment by hpages** [comment]
Excellent. Thanks!
